"""
Test suite for Exercise 2: Score Calibration & Lift Analysis.

Run from the repo root:
    python -m unittest R51795.test_02_score_calibration -v

All tests are based on a deterministic synthetic dataset generated by
exercise_setup.py.
Passing every test means the implementation matches the provided answer key.
"""
import importlib.util
import sys
import unittest
from pathlib import Path

import pandas as pd

# Make sure imports resolve regardless of where the tests are invoked from
_THIS_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _THIS_DIR.parent
for _p in (_THIS_DIR, _REPO_ROOT):
    _p_str = str(_p)
    if _p_str not in sys.path:
        sys.path.insert(0, _p_str)

from exercise_setup import generate_churn_data  # noqa: E402


# ---------------------------------------------------------------------------
# Reference implementation (answer key)
# ---------------------------------------------------------------------------
def _reference_calibrate_and_lift(scores_df: pd.DataFrame, labels_df: pd.DataFrame) -> dict:
    """Canonical implementation derived from the answer key."""
    # 1. Merge – inner join
    df = scores_df.merge(labels_df, on=["account_id", "predict_period_end"], how="inner")

    # 2. Bin into 10 deciles
    df["decile"] = pd.qcut(df["score"], q=10, labels=False, duplicates="drop")

    # 3. Aggregation – mean for calibration and baseline
    calib = df.groupby("decile")["churn_label"].mean()
    baseline = df["churn_label"].mean()

    # 4. Top decile – highest decile label
    top_decile_rate = calib.loc[df["decile"].max()]

    # 5. Lift
    lift = top_decile_rate / baseline

    # 6. Capture – top 10 % most risky
    df_sorted = df.sort_values("score", ascending=False)
    total_churns = df["churn_label"].sum()
    capture_top10 = (
        df_sorted.head(int(len(df_sorted) * 0.10))["churn_label"].sum() / total_churns
    )

    # 7. Tiers – thresholds 0.3 / 0.6
    tiers = pd.cut(
        df["score"], bins=[0.0, 0.3, 0.6, 1.0], labels=["low", "medium", "high"]
    )

    return {
        "baseline_rate": float(baseline),
        "top_decile_rate": float(top_decile_rate),
        "lift": float(lift),
        "capture_top10": float(capture_top10),
        "calibration_by_decile": calib.to_dict(),
        "tiers_example_counts": tiers.value_counts().to_dict(),
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _load_candidate_function():
    """
    Dynamically import calibrate_and_lift from 02_score_callibration.py.
    The leading digit in the filename prevents a normal import.
    """
    module_path = _THIS_DIR / "02_score_callibration.py"
    spec = importlib.util.spec_from_file_location("_score_callibration", str(module_path))
    module = importlib.util.module_from_spec(spec) # type: ignore
    spec.loader.exec_module(module) # type: ignore

    return module.calibrate_and_lift


def setUpModule():
    """Run once for the entire module: generate data and execute both implementations."""

    global _scores_df, _labels_df, _expected, _actual

    _scores_df, _labels_df = generate_churn_data(n=1000)
    _expected = _reference_calibrate_and_lift(_scores_df, _labels_df)

    fn = _load_candidate_function()
    _actual = fn(_scores_df.copy(), _labels_df.copy())


# ---------------------------------------------------------------------------
# Schema tests
# ---------------------------------------------------------------------------

class TestOutputSchema(unittest.TestCase):
    REQUIRED_KEYS = {
        "baseline_rate",
        "top_decile_rate",
        "lift",
        "capture_top10",
        "calibration_by_decile",
        "tiers_example_counts",
    }

    def test_returns_dict(self):
        """calibrate_and_lift must return a dict."""
        self.assertIsInstance(_actual, dict)

    def test_summary_has_required_keys(self):
        """All six summary keys must be present."""
        self.assertTrue(
            self.REQUIRED_KEYS.issubset(_actual.keys()),
            f"Missing keys: {self.REQUIRED_KEYS - set(_actual.keys())}",
        )


# ---------------------------------------------------------------------------
# Baseline tests
# ---------------------------------------------------------------------------

class TestBaselineRate(unittest.TestCase):

    def test_baseline_rate_type(self):
        """baseline_rate must be a float."""
        self.assertIsInstance(_actual["baseline_rate"], float)

    def test_baseline_rate_value(self):
        """baseline_rate must match the reference mean churn rate (±1e-6)."""
        self.assertAlmostEqual(
            _actual["baseline_rate"],
            _expected["baseline_rate"],
            places=6,
            msg="baseline_rate incorrect – use df['churn_label'].mean()",
        )

    def test_baseline_rate_in_unit_interval(self):
        """baseline_rate must be between 0 and 1."""
        self.assertGreaterEqual(_actual["baseline_rate"], 0.0)
        self.assertLessEqual(_actual["baseline_rate"], 1.0)


# ---------------------------------------------------------------------------
# Calibration-by-decile tests
# ---------------------------------------------------------------------------

class TestCalibrationByDecile(unittest.TestCase):

    def test_calibration_has_ten_deciles(self):
        """calibration_by_decile must contain exactly 10 entries."""
        n_deciles = len(_actual["calibration_by_decile"])
        self.assertEqual(
            n_deciles,
            10,
            f"Expected 10 deciles, got {n_deciles} – use q=10 in pd.qcut()",
        )

    def test_calibration_values_are_churn_rates(self):
        """Every decile churn rate must be in [0, 1]."""
        for decile, rate in _actual["calibration_by_decile"].items():
            self.assertGreaterEqual(rate, 0.0, f"Decile {decile} rate < 0")
            self.assertLessEqual(rate, 1.0, f"Decile {decile} rate > 1")

    def test_calibration_values_match_reference(self):
        """Decile churn rates must match the reference implementation (±1e-6)."""
        expected_calib = _expected["calibration_by_decile"]
        actual_calib = _actual["calibration_by_decile"]
        for decile in expected_calib:
            self.assertIn(decile, actual_calib, f"Decile {decile} missing")
            self.assertAlmostEqual(
                actual_calib[decile],
                expected_calib[decile],
                places=6,
                msg=f"Decile {decile} rate incorrect – use .mean() aggregation",
            )


# ---------------------------------------------------------------------------
# Top-decile tests
# ---------------------------------------------------------------------------

class TestTopDecileRate(unittest.TestCase):

    def test_top_decile_rate_value(self):
        """top_decile_rate must match reference (±1e-6)."""
        self.assertAlmostEqual(
            _actual["top_decile_rate"],
            _expected["top_decile_rate"],
            places=6,
            msg="top_decile_rate incorrect – use calib.loc[df['decile'].max()]",
        )

    def test_top_decile_rate_exceeds_baseline(self):
        """A useful model's top-decile rate must exceed the baseline."""
        self.assertGreater(
            _actual["top_decile_rate"],
            _actual["baseline_rate"],
            "top_decile_rate should be higher than baseline_rate for a predictive model",
        )


# ---------------------------------------------------------------------------
# Lift tests
# ---------------------------------------------------------------------------

class TestLift(unittest.TestCase):

    def test_lift_value(self):
        """lift must equal top_decile_rate / baseline_rate (±1e-6)."""
        self.assertAlmostEqual(
            _actual["lift"],
            _expected["lift"],
            places=6,
            msg="lift incorrect – use top_decile_rate / baseline",
        )

    def test_lift_consistent_with_components(self):
        """lift must equal top_decile_rate / baseline_rate as derived from summary."""
        derived_lift = _actual["top_decile_rate"] / _actual["baseline_rate"]
        self.assertAlmostEqual(
            _actual["lift"],
            derived_lift,
            places=6,
            msg="lift is inconsistent with top_decile_rate / baseline_rate",
        )

    def test_lift_greater_than_one(self):
        """Lift for a predictive model should be > 1."""
        self.assertGreater(_actual["lift"], 1.0)


# ---------------------------------------------------------------------------
# Capture tests
# ---------------------------------------------------------------------------

class TestCaptureTop10(unittest.TestCase):

    def test_capture_top10_value(self):
        """capture_top10 must match reference (±1e-4)."""
        self.assertAlmostEqual(
            _actual["capture_top10"],
            _expected["capture_top10"],
            places=4,
            msg=(
                "capture_top10 incorrect – use "
                "df_sorted.head(int(len(df_sorted)*0.10))['churn_label'].sum() / total_churns"
            ),
        )

    def test_capture_top10_in_unit_interval(self):
        """capture_top10 must be between 0 and 1."""
        self.assertGreaterEqual(_actual["capture_top10"], 0.0)
        self.assertLessEqual(_actual["capture_top10"], 1.0)

    def test_capture_top10_exceeds_random_baseline(self):
        """Top 10 % capture should exceed the 10 % random baseline."""
        self.assertGreater(
            _actual["capture_top10"],
            0.10,
            "capture_top10 should be > 0.10 for a model better than random",
        )


# ---------------------------------------------------------------------------
# Tiering tests
# ---------------------------------------------------------------------------

class TestRiskTiers(unittest.TestCase):

    def test_tiers_has_three_labels(self):
        """tiers_example_counts must contain 'low', 'medium', and 'high'."""
        counts = _actual["tiers_example_counts"]
        for label in ("low", "medium", "high"):
            self.assertIn(
                label,
                counts,
                f"Tier '{label}' missing – check pd.cut bins (e.g. [0.0, 0.3, 0.6, 1.0])",
            )

    def test_tiers_counts_are_positive(self):
        """Every tier must have at least one member."""
        for label, count in _actual["tiers_example_counts"].items():
            self.assertGreater(count, 0, f"Tier '{label}' has 0 members")

    def test_tiers_counts_sum_to_total(self):
        """Tier counts must sum to the number of generated accounts."""
        total = sum(_actual["tiers_example_counts"].values())
        self.assertEqual(
            total,
            len(_scores_df),
            "Tier counts do not sum to generated accounts – check merge and bin boundaries",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
